### PR TITLE
made changes to the layouts and fragments

### PR DESCRIPTION
**Pull request by Gmatieso**
I noted the layout resources had warnings , so  i simply created resources in those strings to adhere to android best practice

### CODE REVIEW

**Comment by Gmatieso** [comment]
created strings resource on the layouts and fragments

**Comment by brandy-kay** [comment]
Thanks @Gmatieso

**Comment by Gmatieso** [comment]
welcome @brandy-kay .. Nice Job . we can work awesome staff together

**Comment by brandy-kay** [comment]
Yeah sure we can work as a team and build cool staff together

**Pull request merged**
